name: ci

on:
  push:
    branches:
      - 'releases/v*'
      - 'develop'
    tags:
      - 'v*.*.*'
  workflow_dispatch:


jobs:
  docker:
    runs-on: [self-hosted, multiarch]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set the environment variable
        run: echo REPOSITORY_NAME=${GITHUB_REPOSITORY#*\/} >> $GITHUB_ENV
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4     
        with:
          images: |
            "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY_NAME }}"
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up SSH Node1
        uses:  MrSquaare/ssh-setup-action@v2
        with:
          host: mbp-bruno
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          private-key-name: sshmbp
      - name: Set up SSH Node2
        uses:  MrSquaare/ssh-setup-action@v2
        with:
          host: pc-bruno-gpu
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          private-key-name: sshpcgpu
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
          driver: remote
          endpoint: ssh://pc-bruno-gpu
          platforms: linux/amd64
          append: |
            - endpoint: ssh://bruno@mbp-bruno
              platforms: linux/arm64/v8
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: |
            linux/amd64
            linux/arm64/v8
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
