name: ci

on:
  push:
    branches:
      - 'releases/v*'
      - 'develop'
    tags:
      - 'v*.*.*'
  workflow_dispatch:


jobs:
  docker:
    runs-on: [self-hosted, multiarch]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set the environment variable
        run: echo REPOSITORY_NAME=${GITHUB_REPOSITORY#*\/} >> $GITHUB_ENV
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4     
        with:
          images: |
            "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY_NAME }}"
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:        
          version: v0.10.4
          buildkitd-flags: --debug
          driver: docker-container
          driver-opts: |
            image=moby/buildkit:v0.11.5
            network=host
          endpoint: ssh://bruno@mbp-bruno
          platforms: linux/arm64
          append: |
            - endpoint: ssh://bruno@pc-bruno-gpu
              platforms: linux/amd64
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: |
            linux/amd64
            linux/arm64/v8
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
